<?php

/**
 * Implementation of hook_menu
 */
function strophe_chat_menu() {
  $items['discussion-with/%user'] = array(
    'page callback' => 'strophe_chat_page',
    'page arguments' => array(1),
    'access callback' => 'strophe_chat_access',
    'access arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
    );
  return $items;
}

function strophe_chat_page($other) {
  include_once drupal_get_path('module', 'strophe') .'/strophe.inc';
  global $user;
  return theme('discussion_room', new strophe_user($other));
}

/**
 * Implementation of hook_theme
 */
function strophe_chat_theme() {
  $path = drupal_get_path('module', 'strophe_chat');
  return array(
    'discussion_room' => array(
      'path' => "$path/theme",
      'template' => 'discussion_room',
      'arguments' => array('other' => NULL)),
  );
  
}

function strophe_chat_access($arg) {
  return TRUE;
}