<?php

/**
 * Implementation of hook_menu
 */
function strophe_chat_menu() {
  $items['discussion-with/%'] = array(
    'page callback' => 'strophe_chat_page',
    'page arguments' => array(1),
    'access callback' => 'strophe_chat_access',
    'access arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
    );
  return $items;
}

function strophe_chat_page($name) {
  $other = user_load(array('name' => $name));
  include_once drupal_get_path('module', 'strophe') .'/strophe.inc';
  drupal_add_js(drupal_get_path('module', 'strophe') . '/chat/chat.js');
  $xmpp_other = new strophe_user($other);
  drupal_add_js(array(
    'strophe' => array(
      'chat' => array('other' => $xmpp_other->jid))),
    'setting');
  return theme('chat_room', $other);
}

/**
 * Implementation of hook_theme
 */
function strophe_chat_theme() {
  $path = drupal_get_path('module', 'strophe_chat');
  return array(
    'chat_room' => array(
      'path' => "$path/theme",
      'template' => 'chat_room',
      'arguments' => array('other' => NULL)),
  );
  
}

function strophe_chat_access($arg) {
  return TRUE;
}