<?php

function strophe_roster_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks[0] = array(
        'info' => t('XMPP Roster'),
        'cache' => BLOCK_NO_CACHE,
      );
      return $blocks;
    case 'configure':
      return null;
    case 'save':
    return null;
    case 'view':
      global $user;
      if(0 == $user->uid) {
        return;
      }
      if($delta == 0) {
        $block['subject'] = t('XMPP Roster');
        $block['content'] = theme('strophe_roster');
        return $block;
      }
  }
}

/**
 * Implementation of hook_theme
 */
function strophe_roster_theme() {
  $path = drupal_get_path('module', 'strophe_roster');
  return array(
    'strophe_roster' => array(
      'path' => "$path/theme",
      'template' => 'strophe_roster',
      //'arguments' => array('chatroom' => NULL)
      ),
  );
}
